### ISSUE TITLE
"Could not authorize code_challenge - 754.4"

### ISSUE THREAD

**Issue by Tho1848** [RythenGlyth/EbookDownloader#11]
Script worked perfectly yesterday (Cornelsen). Now I am getting an error message. Must be me system or my mode of operation, but I can#t find the fault. (Other publishers also not working.)

> Logging in and getting Book list
> Logged in successfully
> Got client id: ###
> https://id.cornelsen.de/oxauth/authorize.htm?scope=openid+user_name+roles+cv_sap_kdnr+cv_schule+profile+email+meta+inum&response_type=code&redirect_uri=https%3A%2F%2Funterrichtsmanager.cornelsen.de%2Findex.html&state=9e7255fbd5874f9a51bf6dc343407f13&code_challenge_method=S256&client_id=%40%2138C4.659F.8000.3A79%210001%217F12.03E3%210008%21E3BA.CEBF.4551.8EBD&code_challenge=sGyL54tE1wOfaBrn8rn-3c35mHoZ2jkY1mdC8CfJ0sc&response_mode=query
> TypeError: Cannot read properties of null (reading '1')
>     at C:\Users\###\Documents\EbookDownloader-master\EbookDownloader.js:1088:93
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> Could not authorize code_challenge - 754.4

```

**Comment by runiq** [comment]
I'm still seeing the same error with Cornelsen, I'm afraid. :( I've double checked that I've used the username (instead of email).

I noticed that, when logging in at lernen.cornelsen.de, I had to select "school account". Is your project expected to work with those?
