### ISSUE TITLE
Type Error on Click&Study 

### ISSUE THREAD

**Issue by Aikidooo** [RythenGlyth/EbookDownloader#12]
Moin,
just tried to download an Ebook from CCBuchner, but the script failed for a reason I can't comprehend:
![EbookDownloader Err](https://github.com/user-attachments/assets/2d97569e-a9b7-42fd-9774-714c6d8392cf)
Everything is set up as instructed, are there any special naming conventions for the executables I didn't follow?
This is my directory:
![grafik](https://github.com/user-attachments/assets/2cf0933f-3c36-42b9-ae61-09b1ddfb6688)

I'm a big fan of the project, would appreciate some help

**Comment by RythenGlyth** [comment]
This seems to be the same as #10 . I have no idea what's the problem. I think it's not a problem in this project but in prompts.

For now, try to rerun the script.

**Comment by Aikidooo** [comment]
So I debugged the javascript a little and found out that this error simply occurs due to incorrect credentials but instead of a "login failed" message it tries to fetch the list of available books and passes the resulting empty array to the prompting lib which leads to another counter-intuitive error message.
