### ISSUE TITLE
Npm needs Visual Studio build tools

### ISSUE THREAD

**Issue by Aikidooo** [RythenGlyth/EbookDownloader#16]
Hi again,
I just tried installing the tool on a different device, but it failed because npm install for some reason calls/relies on Visual Studio which I am unable to install properly via winget or the npm package, it just doesn't detect it. Do you know why this is needed in the first place or how to install it properly? I had VS installed of course, but others were struggling alot. Of course there is the Windows installer where you have to manually select the c++ desktop development part, but that wouldn't be automatic installation anymore, right?

The tool is in a bit of a hype at the moment because we have to buy a lot of different Ebooks from different publishers in my class which is quite a mess with all the very bad readers, so I'm kind of the sole dealer of clean pdfs who is able to run the application. 
I really appreciate your work and your openness to contributions, please continue your work!

**Comment by Aikidooo** [comment]
This is the error message
![grafik](https://github.com/user-attachments/assets/52eb6ed1-b09b-45d7-8aa9-98443ee7ddc7)

**Comment by RythenGlyth** [comment]
should be fixed with f082983197bb65e2ade9c47e03b881d93a66894f
mupdf is removed as a dependency, mutool binary is required instead
