### ISSUE TITLE
swiss cornelsen

### ISSUE THREAD

**Issue by ivannunyadambiz** [RythenGlyth/EbookDownloader#17]
hi there.
how would i change this to use the swiss cornelsen interface?
logins from there don't work on the german servers...

**Comment by RythenGlyth** [comment]
If you send me the website and login data of an account with books in it to my mail (my github name @gmail.com), I can have a look at it and maybe add the website to the downloader.

**Comment by RythenGlyth** [comment]
swiss cornelsen is added as of 50fc11768a1f5d9da291938dcb68864792290e4b
