### ISSUE TITLE
book2look error

### ISSUE THREAD

**Issue by ahmed951** [RythenGlyth/EbookDownloader#18]
when I download from book2look it throws this error :

node:internal/crypto/cipher:184
  const ret = this[kHandle].final();
                            ^

Error: error:1C80006B:Provider routines::wrong final block length
    at Decipheriv.final (node:internal/crypto/cipher:184:29)
    at PBKDF2Job.<anonymous> (C:\Users\ju\Documents\GitHub\EbookDownloader\src\downloader\book2look.js:84:67)
    at job.ondone (node:internal/crypto/pbkdf2:55:12) {
  library: 'Provider routines',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_WRONG_FINAL_BLOCK_LENGTH'
}

**Comment by RythenGlyth** [comment]
Can you send a link to what you're trying to download

**Comment by ahmed951** [comment]
https://book2look.com/book/EtkYPliHwN

**Comment by RythenGlyth** [comment]
as it seems, some books are no pdfs but are only stored as images of pages. Currently, there is no easy fix, I would've to write a whole new downloader

**Comment by ahmed951** [comment]
Ok, no problem.
I wrote a python script to download the images then convert it to a PDF file.

Thank you.
