### ISSUE TITLE
Cornelsen doesn't work

### ISSUE THREAD

**Issue by phipangd** [RythenGlyth/EbookDownloader#4]
cornelsen authentication doesn't work, any email or password will give you this error:

`Logging in and getting Book list
Logged in successfully
TypeError: Cannot read properties of null (reading '1')
    at C:\Users\unknown\EbookDownloader\EbookDownloader.js:725:114
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Could not load main.js - 754.2`

**Comment by RythenGlyth** [comment]
commit 4907222 should resolve the issue, if not please reopen the issue
