### ISSUE TITLE
not a clean digital pdf

### ISSUE THREAD

**Issue by phipangd** [RythenGlyth/EbookDownloader#5]
Is it not possible to get pdfs directly from cornelsen instead of jpg’s of the pages? It would result in extremely smaller files and lossless instead of the compressed jpg’s you get which then when merged into a pdf create huge files. The online ebook viewer and offline windows cornelsen app both offer the ebook in lossless quality (infinite zooming). Maybe you could grab it from there? Also the offline Cornelsen app does indeed download a pdf of the ebook but it’s unopenable and probably encrypted. If you want one of those pdfs that the cornelsen app downloaded I can provide one but idk if you can do anything with it.

**Comment by RythenGlyth** [comment]
Last time I checked, Cornelsen didn't have the option to export uncompressed PDFs. The website just loads tiles of the pages (I think 512x512 pixels) and when you zoom in, it just loads more of these tiles but in better quality. They are always images though. The best quality they support is the one with 8192px which should be supported by the downloader.

**Comment by RythenGlyth** [comment]
If you can provide an account with something in it email me: rythenglyth@gmail.com then I can try to reverse engineer the offline download

**Comment by RythenGlyth** [comment]
Feature to download the lossless PDFs is now added with commit 6d57760 .
I'm now working on also adding the assets as links to the PDF

**Comment by RythenGlyth** [comment]
hyperlinks (inside the document and to outside material which is available online e.g. explanatory videos) and the toc also work now
