### ISSUE TITLE
not an issue, just a workaround I used :)

### ISSUE THREAD

**Issue by fabriziosalmi** [RythenGlyth/EbookDownloader#7]
For some reasons axios and cookie jar raised issue on my setup.. then I fixed this way:

```
const axios = require('axios');
const tough = require('tough-cookie');

// Create a cookie jar
const cookieJar = new tough.CookieJar();

// Configure axios instance with cookie jar support
const client = axios.create({
    jar: cookieJar,
    withCredentials: true // Required for cookie jar support
});
```

Setup:
- OS: ubuntu 22
- Node 16 installed via nvm

**Comment by RythenGlyth** [comment]
For what website is this required?

Also feel free to make a pull request

**Comment by fabriziosalmi** [comment]
I tested it against book2look and it worked like a charm :) not tested against others ones. going to PR and TY dear dev, awesome project.
