### ISSUE TITLE
CC Buchner: Login failed

### ISSUE THREAD

**Issue by Jogaxell** [RythenGlyth/EbookDownloader#9]
When trying to download an ebook from CC Buchner the programm throws the following error:
`ccbuchner Login failed - e501`

if you need any additional info please let me know.

**Comment by RythenGlyth** [comment]
Thanks for creating the issue. I can have a look it.
To debug, could you send me a working account with books on it via email? (my name @gmail.com )

**Comment by RythenGlyth** [comment]
should be fixed with f54abba189d44a1543b90690dc7c7ed2a6d303ad
